import api from './client'

export const createJudge = (userId) => api.post('/judges', null, { params: { user_id: userId } }).then(r => r.data)
export const listJudges = () => api.get('/judges').then(r => r.data)
export const createAssignment = (judgeId, teamId, compId) => api.post('/judges/assignments', null, { params: { judge_id: judgeId, team_id: teamId, competition_id: compId } }).then(r => r.data)
export const createBulkAssignments = (judgeId, compId) => api.post('/judges/assignments/bulk', null, { params: { judge_id: judgeId, competition_id: compId } }).then(r => r.data)
export const listAssignments = (judgeId) => api.get('/judges/assignments', { params: { judge_id: judgeId } }).then(r => r.data)
export const deleteAssignment = (assignmentId) => api.delete(`/judges/assignments/${assignmentId}`).then(r => r.data)
export const listEvaluations = (compId) => api.get(`/judges/competitions/${compId}/evaluations`).then(r => r.data)
export const createEvaluation = (judgeId, teamId, compId) => api.post('/judges/evaluations', null, { params: { judge_id: judgeId, team_id: teamId, competition_id: compId } }).then(r => r.data)
export const addScore = (evalId, criterionId, score, comment) => api.post(`/judges/evaluations/${evalId}/scores`, null, { params: { criterion_id: criterionId, score, comment } }).then(r => r.data)
export const clearEvaluation = (evaluationId) => api.delete(`/judges/evaluations/${evaluationId}`).then(r => r.data)
export const correctScore = (evalId, criterionId, score, reason) => api.patch(`/judges/evaluations/${evalId}/scores/correct`, null, { params: { criterion_id: criterionId, score, reason } }).then(r => r.data)
export const listCriteria = () => api.get('/admin/evaluation-criteria').then(r => r.data)
export const createCriterion = (name, weight) => api.post('/admin/evaluation-criteria', null, { params: { name, weight } }).then(r => r.data)
export const listMyAssignments = () => api.get('/judges/my-assignments').then(r => r.data)
export const getCriteria = () => api.get('/judges/evaluations/criteria').then(r => r.data)
export const createMyEvaluation = (teamId, compId) => api.post('/judges/evaluations/mine', null, { params: { team_id: teamId, competition_id: compId } }).then(r => r.data)
export const getCompetitionScores = (compId) => api.get(`/judges/competitions/${compId}/scores`).then(r => r.data)
export const listMyEvaluations = (compId) => api.get('/judges/evaluations', { params: { comp_id: compId } }).then(r => r.data)
export const getJudgeAllSubmissions = () => api.get('/judges/submissions').then(r => r.data)
export const getSubmittedTeams = (compId, onlyWithFiles = false) => api.get('/judges/submitted-teams', { params: { ...(compId ? { comp_id: compId } : {}), ...(onlyWithFiles ? { only_with_files: true } : {}) } }).then(r => r.data)
export const getAllScores = (competitionId) => api.get('/judges/all-scores', { params: { competition_id: competitionId } }).then(r => r.data)
export const getAveragedScores = (competitionId) => api.get('/judges/competitions/' + competitionId + '/averaged-scores').then(r => r.data)
export const populateEvaluations = (competitionId) => api.post('/judges/competitions/' + competitionId + '/populate-evaluations').then(r => r.data)
export const updateEvaluationStatus = (evaluationId, newStatus, reason) => api.post(`/judges/evaluations/${evaluationId}/status`, null, { params: { new_status: newStatus, reason } }).then(r => r.data)
export const getEvaluationAudit = (evaluationId) => api.get(`/judges/evaluations/${evaluationId}/audit`).then(r => r.data)
